### ISSUE TITLE
Snapshot is not correctly written

### ISSUE THREAD

**Issue by khurram18** [smallcorgi/Faster-RCNN_TF#101]
I am training the network and getting this output
```
Wrote snapshot to: /Users/khurram/Development/KFRCNN/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_30.ckpt
done solving

real	3m57.649s
user	17m52.281s
sys	2m33.946s
+ set +x
grep: experiments/logs/faster_rcnn_end2end_VGG16_.txt.2017-03-13_23-00-01: No such file or directory
+ python ./tools/test_net.py --device cpu --device_id 0 --weights --imdb voc_2007_test --cfg experiments/cfgs/faster_rcnn_end2end.yml --network VGGnet_test
voc_2007_train
voc_2007_val
voc_2007_trainval
voc_2007_test
kitti_train
kitti_val
kitti_trainval
kitti_test
nthu_71
nthu_370
usage: test_net.py [-h] [--device DEVICE] [--device_id DEVICE_ID]
                   [--def PROTOTXT] [--weights MODEL] [--cfg CFG_FILE]
                   [--wait WAIT] [--imdb IMDB_NAME] [--comp]
                   [--network NETWORK_NAME]
test_net.py: error: argument --weights: expected one argument
```
There is no `VGGnet_fast_rcnn_iter_30.ckpt` in `output/faster_rcnn_end2end/voc_2007_trainval/` directory(I am only using 30 iterations for quick debugging).

**Comment by lk251** [comment]
Hi @khurram18 , I have the same problem. I'm working to find a solution at the moment.

**Comment by lk251** [comment]
@khurram18 actually the cpkt files are there after I train, only not as I expected. Each snapshot is a group three files, (possible explanation here http://stackoverflow.com/questions/41265035/tensorflow-why-there-are-3-files-after-saving-the-model) even though we use filename.cpkt to refer to them.

However, the test_net.py error I think is due to the log not being created where it should, if at all. This is how the faster_rcnn_end2end.sh file defines the value that goes into the --weights option:

NET_FINAL=`grep -B 1 "done solving" ${LOG} | grep "Wrote snapshot" | awk '{print $4}'`

but the log isn't there.

**Comment by khurram18** [comment]
@lev-kusanagi I just find out the solution. Replace 
```saver = tf.train.Saver(write_version=tf.train.SaverDef.V2)``` 
in `lib\faster_rcnn\demo.py`
Basically the default saver was using V2 in training time and during restore we were using V1.

**Comment by lk251** [comment]
Thanks @khurram18 ! But I'm not sure if that is it. The file demo.py doesn't do any training or snapshots, as far as I can tell.

Both train_net.py and test_net.py seem to not specify write_version:

Saving session in /lib/fast_RCNN/train.py :
```
        self.saver.save(sess, filename)
        print 'Wrote snapshot to: {:s}'.format(filename)
```
Restoring session in /tools/test_net.py : 
```
    # start a session
    saver = tf.train.Saver()
    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
    saver.restore(sess, args.model)
    print ('Loading model weights from {:s}').format(args.model)
```

There must be some other problem.

**Comment by khurram18** [comment]
@lev-kusanagi The init function of `Saver` object has a default value of `V2` for version number.
```
def __init__(self,
               var_list=None,
               reshape=False,
               sharded=False,
               max_to_keep=5,
               keep_checkpoint_every_n_hours=10000.0,
               name=None,
               restore_sequentially=False,
               saver_def=None,
               builder=None,
               defer_build=False,
               allow_empty=False,
               write_version=saver_pb2.SaverDef.V2,
               pad_step_number=False):
```
Just open `saver.py` in `path where your tensorflow is installed/python/training/saver.py`

**Comment by lk251** [comment]
@khurram18 Thank you. I'm afraid that doesn't solve the issue with faster_rcnn_end2end.sh. The reason is that tf.train.Saver produces three files of extensions .ckpt.meta, .ckpt.index, and ckpt.data and therefore os.path.exists('filename.ckpt') (which is used in test_net.py) does not work. 

I've fixed this in https://github.com/lev-kusanagi/Faster-RCNN_TF/commit/c15c4890d30db7f41530cd20a4be1aedcde3d5f6 and https://github.com/lev-kusanagi/Faster-RCNN_TF/commit/7b071cc1c9ba8257c253ff7888ecf64b666a1271 (I forgot to include the latter in the former.)

but it still won't work because of #107 (the location of the snapshot directory is dependent on the creation of a log file, which is not being created).

**Comment by LHagendoorn** [comment]
I'm assuming that you have fixed this by now, but you can solve the log problem by simply creating the logs folder it is missing ;) I have used this implementation to train and test on MS_COCO, my changes to make that work can be found [here](https://github.com/smallcorgi/Faster-RCNN_TF/compare/master...TheLaurens:master)

**Comment by lk251** [comment]
Thanks @TheLaurens !! :)

**Comment by hadign20** [comment]
@khurram18 Hi. I have a similar problem as this. After training a dataset based on pascal VOC format, it keeps showing this message repeatedly and nothing happens:

`Waiting for /home/hadi/Software/tensorflow/TEST_FRCN_ROOT/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_20.ckpt to exist...`

![screenshot from 2017-06-03 20-28-53](https://cloud.githubusercontent.com/assets/24352869/26757878/16956144-48e1-11e7-835c-6ad6bb81c5fc.png)

the 3 files you mentioned are created, but this message doesn't stop prompting.

How can I fix the version problem. I can't find the `/python/training/saver.py` or `lib\faster_rcnn\demo.py` files anywhere.

**Comment by Almonfrey** [comment]
I think the below problem happens when you do not have a "logs" dir inside "experiments" dir...

grep: experiments/logs/faster_rcnn_end2end_VGG16_.txt.2017-03-13_23-00-01: No such file or directory

So, the log file is not created and the grep command doesn't return the right path to NET_FINAL, just before the test stage starting...

NET_FINAL=`grep -B 1 "done solving" ${LOG} | grep "Wrote snapshot" | awk '{print $4}'`

After creating "logs" dir, you should also consider:

https://github.com/smallcorgi/Faster-RCNN_TF/issues/79

This must solve the "waiting" problem... These steps worked for me.
