### ISSUE TITLE
Training instruction

### ISSUE THREAD

**Issue by ck196** [smallcorgi/Faster-RCNN_TF#3]
Can you provide training instruction?
I want to train on my own data with PASCAL_VOC format.

Thank you.

**Comment by yfor1008** [comment]
i train my own data as follows：
1. download pascal_voc data, put it in "Faster-RCNN_TF/data/"
2. use my own data to replace the data of pascal_voc 
3. change **config.py** in “Faster-RCNN_TF/lib/fast_rcnn/”, **pascal_voc.py** in "Faster-RCNN_TF/lib/datasets/", **VGGnet_train.py** in "Faster-RCNN_TF/lib/networks/"
4. use **tools/train_net.py** to train.

**Comment by ck196** [comment]
@yfor1008 Thank you very much.
I got it now.

**Comment by zacwellmer** [comment]
@ck196 @yfor1008 What exactly are you changing in config.py, pascal_voc.py, and VGGnet_train.py?

**Comment by abhiML** [comment]
@zacwellmer  did you get the answer?

**Comment by kalanityL** [comment]
Lets call your new Dataset mydata 

1/ In lib/datasets 

1.1 - Add a file mydata.py and mydata_eval.py following pascal_voc.py and voc_eval.py to describe the organization of your folders and file parsing of your data. 
(you can also get inspiration from there: https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md) 
In particular in mydata.py that describes your data set, give all the information about it. 
Regarding the self._classes, keep __background__ and add the other classes
For instance if you want to do bounding boxes only around bottles, do: 
```
self._classes = ('__background__', # always index 0
                         'bottles')
```

1.2 - edit factory.py by adding at the start a line for your new dataset 
`from datasets.mydata import mydata
`
at the end of the file, add the info for your dataset. For instance
```
mydata_devkit_path = ThePathToYourData
for split in ['train', 'test']:
    name = '{}_{}'.format('mydata', split)
    __sets[name] = (lambda split=split: boats(split, "000",mydata_devkit_path)) #I kept the structure with the string for the year by laziness, and just don't use it. you can remove it
``` 

2. In lib/network
change the number of class n_classes in VGGnet_test.py and VGGnet_train.py to fit your number of classes

Hope it will help

**Comment by zjz5250** [comment]
@kalanityL 
 if i change the dataset as your description, shall  i need to change the pretrain model? 
the code in train.py as follows:
 "if self.pretrained_model is not None:
            print ('Loading pretrained model '
                   'weights from {:s}').format(self.pretrained_model)
            self.net.load(self.pretrained_model, sess, self.saver, True)"
i do need  this  part any more,do i?

**Comment by zjz5250** [comment]
@kalanityL
   i don't know the function of the VGG_imagenet.npy. when run the code of github, the pretrain model can be loaded.  so if i want to run my own dataset ,do i need to change the pretain model? or let it unchanged

**Comment by gentlebreeze1** [comment]
how to change the code @yfor1008

**Comment by yfor1008** [comment]
@gentlebreeze1 
>  i train my own data as follows：
> 
> download pascal_voc data, put it in "Faster-RCNN_TF/data/"
> use my own data to replace the data of pascal_voc
> change `config.py` in “Faster-RCNN_TF/lib/fast_rcnn/”, `pascal_voc.py` in "Faster-RCNN_TF/lib/datasets/", `VGGnet_train.py` in "Faster-RCNN_TF/lib/networks/"
> use tools/train_net.py to train.

in `config.py`, i changed the `minibatch`, `RPN`, etc; in `pascal_voc.py` and `VGGnet_train.py`, i changed the labels

**Comment by gentlebreeze1** [comment]
中国人么？能不能把你修改后的代码传给我一份我看看。谢谢了
are you  chinese？ Can you send me the modified code?my  email is 914672556@qq.com。thanks @yfor1008

**Comment by gentlebreeze1** [comment]
AssertionError: Path does not exist: /home/c303/student/yongzhang/Faster-RCNN_TF/data/VOCdevkit2007/VOC2007/JPEGImages/.jpg

**Comment by yfor1008** [comment]
@gentlebreeze1   https://github.com/yfor1008/Faster-RCNN_TF

**Comment by gentlebreeze1** [comment]
Thanks very much for your answer @yfor1008 
i have 2 classes,i change classes into 3 in VGGtest.py and VGGtrain.py inside lib/networks.
is the problem related to the follows?
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format has been deprecated.
WARNING:tensorflow:Consider switching to the more efficient V2 format:
WARNING:tensorflow: tf.train.Saver(write_version=tf.train.SaverDef.V2)
WARNING:tensorflow:now on by default.
WARNING:tensorflow:*******************************************************
Traceback (most recent call last):
File "./tools/test_net.py", line 99, in 
saver.restore(sess, args.model)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1439, in restore
{self.saver_def.filename_tensor_name: save_path})
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
run_metadata_ptr)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
feed_dict_string, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
target_list, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [21]
[[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@cls_score/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](cls_score/biases, save/RestoreV2_2/_5)]]

Caused by op u'save/Assign_2', defined at:
File "./tools/test_net.py", line 97, in 
saver = tf.train.Saver()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1051, in init
self.build()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1081, in build
restore_sequentially=self._restore_sequentially)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
restore_sequentially, reshape)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 414, in _AddRestoreOps
assign_ops.append(saveable.restore(tensors, shapes))
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
self.op.get_shape().is_fully_defined())
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
use_locking=use_locking, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
op_def=op_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in init
self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [21]
[[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@cls_score/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](cls_score/biases, save/RestoreV2_2/_5)]]

**Comment by yfor1008** [comment]
> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [21]

The number of categories does not match， do you change the `pascal_voc.py`

**Comment by gentlebreeze1** [comment]
i just change follows:
 self._classes = ('__background__', # always index 0
                         'people','punch')
what else should i do? @yfor1008

**Comment by gentlebreeze1** [comment]
i download your files and change classeslabels.py .same problem occurs.it seems classess problem. @yfor1008

**Comment by yfor1008** [comment]
Check `VGG_train.py` and `VGG_test.py` to see if the number of categories is 3

**Comment by gentlebreeze1** [comment]
yeah,i change n_classes into 3 in VGGnet_train.py under lib/networks floder. the problem still occurs. @yfor1008

**Comment by gentlebreeze1** [comment]
yeah,i change n_classes into 3 in VGGnet_train.py and VGGnet_test.py under lib/networks floder. the problem still occurs. @yfor1008

**Comment by yfor1008** [comment]
`tensorflow` may have made some changes when reading data, the number of categories here should be modified：
```
n_classes = len(class_labels) + 1
```
The number of categories needs +1

**Comment by gentlebreeze1** [comment]
thanks very much @yfor1008 ,but i get the other problem,as following:
 File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/home/c303/student/yongzhang/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 264, in train_net
    sw.train_model(sess, max_iters)
  File "/home/c303/student/yongzhang/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 198, in train_model
    self.snapshot(sess, iter)
  File "/home/c303/student/yongzhang/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 61, in snapshot
    sess.run(net.bbox_weights_assign, feed_dict={net.bbox_weights: orig_0 * np.tile(self.bbox_stds, (weights_shape[0], 1))})

ValueError: operands could not be broadcast together with shapes (4096,16) (4096,12)

**Comment by yfor1008** [comment]
1, to ensure correct modification;
2, clear the output directory and intermediate results;

Re-train again

**Comment by gentlebreeze1** [comment]
Hi ,guy. @yfor1008  i get new one:
Evaluating detections
Writing people VOC results file
Writing punch VOC results file
VOC07 metric? Yes
Reading annotation for 1/170
Traceback (most recent call last):
  File "./tools/test_net.py", line 97, in <module>
    test_net(sess, network, imdb, weights_filename)
  File "/home/c303/student/yongzhang/ai/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 345, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/c303/student/yongzhang/ai/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 321, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/c303/student/yongzhang/ai/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 284, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/c303/student/yongzhang/ai/Faster-RCNN_TF/tools/../lib/datasets/voc_eval.py", line 109, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "/home/c303/student/yongzhang/ai/Faster-RCNN_TF/tools/../lib/datasets/voc_eval.py", line 19, in parse_rec
    obj_struct['pose'] = obj.find('pose').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by yfor1008** [comment]
> AttributeError: 'NoneType' object has no attribute 'text'

Do not find `pose`, check your `xml` file to see if the same with the VOC, and check the file path

**Comment by gentlebreeze1** [comment]
Thank you for your guidance during this time @yfor1008 .I have been running successfully on my dataset.

**Comment by gentlebreeze1** [comment]
if i want to test my pictures use demo.py.where should i change @yfor1008

**Comment by kalanityL** [comment]
@zjz5250 VGG is a classification network, it is "included" in FasterRCNN. The VGG_imagenet.npy is a modele for the VGG classifier trained on the IMAGENET dataset. 
Even if you want to fine tune FasterRCNN on your own dataset, you will want to keep VGG_imagenet.npy loaded at the start of your training for initialization of the weight of the VGG part of FasterRCNN.

**Comment by SilencerChen** [comment]
@yfor1008 I am trying to train on the Visual Genome dataset , I get .json from it . Should I translate the json file into xml just like pascal_voc or try to train it like coco ?
