### ISSUE TITLE
How to run the demo.py in tools directory? 

### ISSUE THREAD

**Issue by KarryWang** [smallcorgi/Faster-RCNN_TF#8]
I try 'python demo.py --model model_path(where is I put the VGG16_imagenet.npy)', but failed.
do i get the right model? 
please give me some help, thanks

**Comment by XiZiler** [comment]
I have encountered nearly the same problem.  run:

`python demo.py --model VGG_imagenet.npy`

I got wrong messages like this:

>Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:07:00.0)
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/rpn_cls_score:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("rpn_cls_prob_reshape:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_bbox_pred/rpn_bbox_pred:0", shape=(?, ?, ?, 36), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rois:0", shape=(?, 5), dtype=float32)
[<tf.Tensor 'conv5_3/conv5_3:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'rois:0' shape=(?, 5) dtype=float32>]
Tensor("fc7/fc7:0", shape=(?, 4096), dtype=float32)
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:940] Data loss: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    saver.restore(sess, args.model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1129, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.DataLossError: Unable to open table file ./VGG_imagenet.npy: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
	 [[Node: save/restore_slice/_2 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_71_save/restore_slice", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Caused by op u'save/restore_slice', defined at:
  File "demo.py", line 116, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 519, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 272, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 187, in restore_op
    preferred_shard=preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 203, in _restore_slice
    preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

**Comment by smallcorgi** [comment]
Hi all,
If you want to run ./tools/demo.py, you should try 
./tools/demo.py --model /path/to/VGGnet_fast_rcnn_iter_70000.ckpt

By the way, VGG_imagenet.npy is a pre-trained model for training a new model.

**Comment by XiZiler** [comment]
@smallcorgi That's great!! Thank you~~

But now I am wondering if I can compile in a pure CPU environment. There are many GPU dependencies in the source code.  Here is what I do:

- modify `setup.py`

```
    #CUDA = locate_cuda()

    #Extension('nms.gpu_nms',
    #    ['nms/nms_kernel.cu', 'nms/gpu_nms.pyx'],
    #    library_dirs=[CUDA['lib64']],
    #    libraries=['cudart'],
    #    language='c++',
    #    runtime_library_dirs=[CUDA['lib64']],
        # this syntax is specific to this build system
        # we're only going to use certain compiler args with nvcc and not with gcc
        # the implementation of this trick is in customize_compiler() below
    #    extra_compile_args={'gcc': ["-Wno-unused-function"],
    #                        'nvcc': ['-arch=sm_35',
    #                                 '--ptxas-options=-v',
    #                                 '-c',
    #                                 '--compiler-options',
    #                                 "'-fPIC'"]},
    #    include_dirs = [numpy_include, CUDA['include']]
    #)
```

- modify `make.sh`

```
   # nvcc -std=c++11 -c -o roi_pooling_op.cu.o roi_pooling_op_gpu.cu.cc \
   #                     -I $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_52
   # g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
   #                      roi_pooling_op.cu.o -I $TF_INC -fPIC -lcudart -L $CUDA_PATH/lib64
   
    g++ -std=c++11 -shared  -o roi_pooling.so roi_pooling_op.cc -I $TF_INC -fPIC  -D_GLIBCXX_USE_CXX11_ABI=0
```
  
- modify `fast_rcnn/nms_wrapper.py`

```
def nms(dets, thresh, force_cpu=False):
    """Dispatch to either CPU or GPU NMS implementations."""

    if dets.shape[0] == 0:
        return []
    #if cfg.USE_GPU_NMS and not force_cpu:
    #    return gpu_nms(dets, thresh, device_id=cfg.GPU_ID)
    #else:
    return cpu_nms(dets, thresh)
```

and then I got the `roi_pooling.so` successfully. 

But when I run `demo.py`, I got a run message like this:

```
Traceback (most recent call last):
  File "../tools/demo.py", line 11, in <module>
    from networks.factory import get_network
  File "/home/xi/Faster-RCNN_TF/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/xi/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "/home/xi/Faster-RCNN_TF/tools/../lib/networks/network.py", line 3, in <module>
    import roi_pooling_layer.roi_pooling_op as roi_pool_op
  File "/home/xi/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 63, in load_op_library
    raise errors._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors.NotFoundError: /home/xi/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _Z22ROIPoolBackwardLaucherPKffiiiiiiiS0_PfPKiRKN5Eigen9GpuDeviceE
```

It seems that there are still some GPU related code that I am not noticed. I will be extremely appreciate if you could give me some advice.

**Comment by XiZiler** [comment]
@smallcorgi That's great. It really works. Thank you~

**Comment by KarryWang** [comment]
@smallcorgi thanks you very much ^_^
